### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by leaftail1880** [leaftail1880/xdnevnik#41]
экран оценок по предмету:
- [ ] всего оценок
- [ ] удалить одну возможную
- [ ] сортировка не по дате выставления

экран оценок
- [ ] до 5 еще 8
- [ ] аттестация 2/5
- [ ] прочитанные/непрочитанные оценки
- [ ] время до урока/в уведомлении в секундах
- [ ] задержка звонка в секундах
- [ ] добавить урок
- [ ] кастомное время уведы перед уроком

меню инструментов
- [ ] список всех учителей / ср балла их предметов
- [ ] отдельный калькулятор оценок
- [ ] собрать портфель

настройки
- [ ] экспорт/импорт настроек
- [ ] автоочистка кэша

код
- [ ] рефакторинг AsyncStore
